%% GraphNicheResults
% Graphs the results of the niche succession simulations

% Need to open the Model results file first for the gg global variable

PercentageSCAge = zeros(gg.numDiv,(gg.initS+1));

h = waitbar(0,'Analysing results within parameter file...please wait');

for jj = 1 : gg.numDiv
    
    for mm = 1 : gg.initS+1

%         Pera = find(gg.MutatedSCAgeFinal(jj,:) == (mm-1));
            Pera = find(gg.MutatedSCAgeFinalCorr(jj,:) == (mm-1));
        %     Pera = find(gg.MutatedSCAgeFinalCorr2(jj,:) == (mm-1));
        Perb = (numel(Pera) / gg.numRuns)*100;
        PercentageSCAge(jj,mm) = Perb;
        
    end
    
    waitbar(jj/gg.numDiv,h)
    
end

delete(h)

% mean the results to attain a results table comparible to experimental
% results

tenYears = mean(PercentageSCAge(1:521,:));
twentyYears = mean(PercentageSCAge(522:1042,:));
thrityYears = mean(PercentageSCAge(1043:1563,:));
fortyYears = mean(PercentageSCAge(1564:2084,:));
fiftyYears = mean(PercentageSCAge(2085:2605,:));
sixtyYears = mean(PercentageSCAge(2606:3126,:));
seventyYears = mean(PercentageSCAge(3127:3647,:));
eightyYears = mean(PercentageSCAge(3648:4168,:));
ninetyYears = mean(PercentageSCAge(4169:4689,:));
hundredYears = mean(PercentageSCAge(4690:5210,:));


meanAgeBrackets = [twentyYears; thrityYears;...
    fortyYears; fiftyYears; sixtyYears; seventyYears ;...
    eightyYears]';

meanAgeBrackets2 = meanAgeBrackets / 100;


%% Graph the results

figure('position' , [200 400 1000 700])
subplot(2,1,1)
bar(meanAgeBrackets(2:end,:))
set(gca, ...
    'Box'         , 'off'     ,...
    'TickDir'     , 'out'     ,...
    'TickLength'  , [.01 .01] ,...
    'XColor'      , 'k'       ,...
    'YColor'      , 'k'       ,...
    'XTick'       , 0:1:5    ,...
    'LineWidth'   , 2         ,...
    'FontSize'    , 8       ,...
    'XTick'       , 1:5       ,...
    'XTickLabel',{'20','40','60','80','100'});
xlabel('Percentage COX deficiency of individual crypts',...
    'FontWeight','Bold','FontSize',12);
ylabel('Percentage of total crypts',...
    'FontWeight','Bold','FontSize',12);
legend('10-20years','20-30years','30-40years',...
    '40-50years','50-60years','60-70years','70-80years',...
    'Location','NorthEastOutside');

set(gca, ...
    'Box'         , 'off'     ,...
    'TickDir'     , 'out'     ,...
    'TickLength'  , [.01 .01] ,...
    'XColor'      , 'k'       ,...
    'YColor'      , 'k'       ,...
    'XTick'       , 0:1:5    ,...
    'LineWidth'   , 2         ,...
    'FontSize'    , 8       ,...
    'XTick'       , 1:5       ,...
    'XTickLabel',{'20','40','60','80','100'});
xlabel('Percentage COX deficiency of individual crypts',...
    'FontWeight','Bold','FontSize',12);
ylabel('Percentage of total crypts',...
    'FontWeight','Bold','FontSize',12);
legend('10-20years','20-30years','30-40years',...
    '40-50years','50-60years','60-70years','70-80years',...
    'Location','NorthEastOutside');
title(gg.finalFilename, 'FontSize', 16, 'FontWeight', 'Bold');

subplot(2,1,2)
bar(gg.MultipleMutRecordResult(1:5))
axis([0, 6, 0, 100]);
set(gca, ...
    'YTick'         ,            0:10:100 ,...
    'TickDir'       ,           'out' ,...
    'TickLength' ,           [.01 .01] ,...
    'Box'             ,           'off' ,...
    'LineWidth'   ,           2);

xlabel('Number of mutations within individual stem cells',...
    'FontWeight','Bold','FontSize',12);
ylabel('Percentage of cells with mutations',...
    'FontWeight','Bold','FontSize',12);

            
        
        